### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mzeidhassan** [amake/SuperTMXMerge#4]
First, thanks for the tool.

I am using the combine functionality on a Windows 10 machine. I am testing the tool with 2 TMX files ". Each file is 80 MB in size. I keep getting this error.

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
```

Do I need to change something in SuperTMXMerge.bat file to increase the memory?

Thanks,
MZ

P.S. Just in case, here is the full error.

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Arabic_TM (The system cannot find the file specified)
        at org.madlonkay.supertmxmerge.CombineIOController$CombineWorker.done(CombineIOController.java:182)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Arabic_TM (The system cannot find the file specified)
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at javax.swing.SwingWorker.get(Unknown Source)
        at org.madlonkay.supertmxmerge.CombineIOController$CombineWorker.done(CombineIOController.java:179)
        ... 20 more
Caused by: java.io.FileNotFoundException: Arabic_TM (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.madlonkay.supertmxmerge.data.JAXB.JAXBTmx.<init>(JAXBTmx.java:212)
        at org.madlonkay.supertmxmerge.CombineIOController$CombineWorker.doInBackground(CombineIOController.java:153)
        at org.madlonkay.supertmxmerge.CombineIOController$CombineWorker.doInBackground(CombineIOController.java:126)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at org.madlonkay.supertmxmerge.CombineIOController$1.run(CombineIOController.java:112)
        at org.madlonkay.supertmxmerge.util.GuiUtil.safelyRunBlockingRoutine(GuiUtil.java:97)
        at org.madlonkay.supertmxmerge.CombineIOController.go(CombineIOController.java:109)
        at org.madlonkay.supertmxmerge.SuperTmxMerge.combineTo(SuperTmxMerge.java:113)
        at org.madlonkay.supertmxmerge.Main.main(Main.java:78)
```

**Comment by amake** [comment]
The stack trace you posted is a different error: `java.io.FileNotFoundException: Arabic_TM (The system cannot find the file specified)`. The solution to this is probably to double-check the path to the TM.

For the out-of-memory error, yes, I suggest you try increasing the JVM heap size. I don't use Windows so I can't give you the exact invocation, but it looks like setting the `JAVA_OPTS` environment variable to `-Xmx2g` (for 2 GB of heap memory) should work. If your Windows shell is like a bash shell that would be like this from the shell:

```bash
JAVA_OPTS=-Xmx2g SuperTMXMerge.bat
```

If you want to be able to double-click the .bat, set `DEFAULT_JVM_OPTS` at the top of the .bat.

**Comment by mzeidhassan** [comment]
Thanks @amake for your reply.

This is strange, because on Windows, a GUI opens once I click on the .bat file and I simply go to the "Combine" tab, click the + sign, add the 2 files to combine, but I keep getting the same error.

I also increased the heap size following this https://www.wikihow.com/Increase-Java-Memory-in-Windows-7

Maybe, a reboot will fix things. I will give it a try. I didn't notice the I/O error indeed, because I didn't expect it. 

Any idea how the file is not found while I browse through the GUI and add the files. By the way, I put the files in the same directory where the .bat file is. 

Thanks again for your support!

**Comment by mzeidhassan** [comment]
It worked fine on my Linux machine. So, I am closing this issue. Thanks for your support.
